### ISSUE TITLE
Travis for `example` dir

### ISSUE THREAD

**Issue by lmatteis** [cyclejs-community/redux-cycles#17]
So I'd like to test the `example` project (which is meant to be a separate project with its own package.json) using travis. Any thoughts on configuring this? @nickbalestra

**Comment by nickbalestra** [comment]
why not making this into a monorepo? Perhpash using something like [lerna](https://github.com/lerna/lerna/) for example..

**Comment by nickbalestra** [comment]
Othwerwise You can set a script field in the travis yaml config:

something like:

```
...
script: cd npm install && npm test && cd ../example && npm install && npm test
```

[Here](https://lord.io/blog/2014/travis-multiple-subdirs/) a cool post about it

**Comment by lmatteis** [comment]
Thanks! That works. I'm getting the cycle/time problem also on travis https://travis-ci.org/cyclejs-community/redux-cycle-middleware/builds/196599833#L1046

Reference PR: https://github.com/cyclejs-community/redux-cycle-middleware/pull/18

**Comment by nickbalestra** [comment]
Weird, as I see it was correctly installed -> https://travis-ci.org/cyclejs-community/redux-cycle-middleware/builds/196599833#L664

**Comment by lmatteis** [comment]
Maybe it's something with how mocha runs/compiles the code? Not sure

**Comment by lmatteis** [comment]
Even with `jest` it fails: https://travis-ci.org/cyclejs-community/redux-cycle-middleware/builds/196612034#L1246

**Comment by lmatteis** [comment]
Maybe @goshakkk @Widdershin can help solve the mystery?

**Comment by lmatteis** [comment]
This is closed as it was a problem with cyclejs/time and the fact that it was compiling into Index.js rather than index.js
