### ISSUE TITLE
Typescript definitions are not added to the build

### ISSUE THREAD

**Issue by bzums** [cyclejs-community/redux-cycles#40]
Hey,

it seems like there are typescript type definitions (see #37) but there are not added to the build and therefore not available when using this lib in your project without further ado. 

Or am I missing something here? If not, I would happily provide a PR.

Best

**Comment by bzums** [comment]
Ah ok I think the version is just not published with type informations, so would it be possible to do so?

Best

**Comment by Widdershin** [comment]
@bzums go ahead and make a pull request 👍

**Comment by bzums** [comment]
@Widdershin would it also be possible to publish version `0.4.1` to npm or are there any reasons speaking against it?

**Comment by Widdershin** [comment]
I don't have publish rights so that would be up to Luca or Nick.

**Comment by nickbalestra** [comment]
Same. @lmatteis feel free to add me and Nick as publisher so we can help with that

**Comment by lmatteis** [comment]
Sorry for the late reply. Should be on npm now :)
