### ISSUE TITLE
Is this project still active/maintained?

### ISSUE THREAD

**Issue by loganpowell** [cyclejs-community/redux-cycles#46]
There seems a steep drop off in activity as of late and open issues that seem a bit stale. Just curious as to how likely I would be to get help if I ended up using your seemingly wonderful library.

**Comment by loganpowell** [comment]
I'll take that as a no.

**Comment by Widdershin** [comment]
Are you interested in stepping up as a maintainer? I would check in with Luca and Nick but if they're super busy I'm sure they'd like the help.
