### ISSUE TITLE
Support multiple stream libraries

### ISSUE THREAD

**Issue by lmatteis** [cyclejs-community/redux-cycles#6]
Currently `createCycleMiddleware()` decides which stream library to use and it defaults `xstream-run`. It would be nice to allow users to select which `run` method to call, hence which stream library to use - and our driver internally should support most common stream libs using `runStreamAdapter`.

**Comment by lmatteis** [comment]
@goshakkk @nickbalestra I'm thinking of this:

```js
// `Cycle` can be xstream or rxjs or anything else
var output = Cycle.run(main, { ACTION: makeActionDriver(), STATE: makeStateDriver() })
const cycleMiddleware = createCycleMiddleware(output);
```

Problem is that the ACTION driver needs access to `store` so we need to create the drivers in the middleware (as it is now).

Maybe we can just keep the API as it is, but add an extra arg to `createCycleMiddleware` which is the actual `run` method to use internally:

```js
import {run} from '@cycle/xstream-run';
const cycleMiddleware = createCycleMiddleware(main, { HTTP: makeHTTPDriver() }, run);
```

Thoughts?

**Comment by goshakkk** [comment]
The second one with passing `run` looks more appropriate. 

One thing worth keeping in mind is the fact that Cycle might become xstream-only internally and will make users themselves responsible for converting sources from xstreams and sinks to xstream if they choose to use another library. It's not set in stone yet, of course, but here is the thread for reference: https://github.com/cyclejs/cyclejs/issues/425

**Comment by nickbalestra** [comment]
Agree with Gosha. Perhaps defaulting to xstream if !run ?

**Comment by lmatteis** [comment]
Interesting, does this mean that all drivers must be xstream compatible?

**Comment by lmatteis** [comment]
@goshakkk it doesn't seem like Cycle will be xstream-only: https://gitter.im/cyclejs/cyclejs?at=585bcfc496a565f844067997

Unless I misunderstood what you were trying to say.

**Comment by lmatteis** [comment]
Ah it seems that the only difference is that we won't have to use runStreamAdapter. But passing the `run` is something that we'll need to do in order to support other stream libs.
