### ISSUE TITLE
Linter

### ISSUE THREAD

**Issue by nickbalestra** [cyclejs-community/redux-cycles#9]
I wanted to add some linting to the project, any suggestion/preferences? (my +1 goes for standard)

**Comment by lmatteis** [comment]
I don't have much experience with this. What's most common in the FRP community?

**Comment by nickbalestra** [comment]
couple of options:

- standard
- prettier (suggested by @staltz)

**Comment by lmatteis** [comment]
What about using eslint?

**Comment by Widdershin** [comment]
I have used eslint, it's fast and great and can fix most issues automatically.

I would highly recommend it.
